name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/hello-devops
  SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  API_KEY: ${{ secrets.RENDER_API_KEY }}

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas unitarias
        run: |
          pytest -q

      - name: Autenticar en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Subir imagen a Docker Hub
        run: |
          docker push $IMAGE_NAME:latest

      - name: Desplegar a Render
        if: env.SERVICE_ID != '' && env.API_KEY != ''
        run: |
          curl -X POST https://api.render.com/v1/services/$SERVICE_ID/deploys \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d ''
