name: CI/CD Pipeline

# Trigger the workflow on pushes or pull requests targeting the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    env:
      # Compose the Docker image name using the Docker Hub username secret
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/hello-devops
      SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      API_KEY: ${{ secrets.RENDER_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run unit tests
        run: |
          pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Render (optional)
        # Only run if the Render secrets are provided
        if: ${{ env.SERVICE_ID != '' && env.API_KEY != '' }}
        run: |
          echo "Triggering deploy on Render service ${{ env.SERVICE_ID }}"
          curl -s -X POST \
            -H "Authorization: Bearer ${{ env.API_KEY }}" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/${{ env.SERVICE_ID }}/deploys
